#!/usr/bin/env bash
cd $(cd $(dirname $0); pwd)

if [ ! -f "./ER" ]; then
lua ./EORO.lua
exit;
else
Token=`cat ./ER`
BotId=`echo $Token | cut -f1 -d":"`
BotUser=$(redis-cli get ${BotId}:BotUser:)
if [[ $BotUser == "" ]]; then
rm -fr ./ER
lua ./EORO.lua
exit;
fi
fi

chmod +x ./tg

if [ "$1" == "F" ]; then
while(true) do
sudo rm -fr ~/.telegram-cli
./tg -s ./EORO.lua $@ --bot=$Token
done
else
if ! screen -list | grep -q "$BotUser"; then
screen -S $BotUser ./FA F
else
screen -X -S $BotUser quit
screen -S $BotUser ./FA F
fi
fi
